name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
        if: matrix.os == 'ubuntu-latest'
      - name: Run CI
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ci-flow
        env:
          CARGO_MAKE_RUN_CODECOV: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
