name: Publish
on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
      - name: Login
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: publish-flow
        env:
          CARGO_MAKE_RUN_CODECOV: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
